### ISSUE TITLE
UnicodeDecodeError on MacOS

### ISSUE THREAD

**Issue by ShawnO33** [Foxy-null/AnkiCraft#1]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-14.0-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-09-17 17:34:24
Add-ons possibly involved: ⁨AnkiCraft⁩

Traceback (most recent call last):
  File "aqt.main", line 609, in loadCollection
  File "aqt.main", line 712, in moveToState
  File "aqt.main", line 718, in _deckBrowserState
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 80, in repl
  File "aqt.deckbrowser", line 73, in show
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 81, in repl
  File "/Users/User1/Library/Application Support/Anki2/addons21/368161874/main.py", line 245, in inject_medals_with_js
    view(
  File "/Users/User1/Library/Application Support/Anki2/addons21/368161874/views.py", line 32, in TodaysMedalsJS
    html=MedalsOverview(
  File "/Users/User1/Library/Application Support/Anki2/addons21/368161874/views.py", line 125, in MedalsOverview
    template = Template(f.read())
  File "encodings.ascii", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 296: ordinal not in range(128)

**Comment by Foxy-null** [comment]
Thank you for reporting an issue!
Seems like this error occurs only on MacOS, so I can't check whether this error is fixed because I'm on Windows environment.

I've just updated it now!([v1.0.9](https://github.com/Foxy-null/AnkiCraft/releases/tag/v1.0.9)) Please let me know whether the issue fixed!

**Comment by ShawnO33** [comment]
Thank you so much! I can't believe you fixed it so quickly. By any chance, does the /give command in Minecraft claim the items? Is there anything you have to do in Minecraft or in the game? I don't play Minecraft often, but I love starting a world with the things I earn in anki.  
Also one last comment (request) what is the addon that displays the total time this week and and last week? Thank you again for your time!

**Comment by Foxy-null** [comment]
That's good to hear! I've actually known about this error for a while now, and I'm glad I finally fixed it! Yay!


> does the /give command in Minecraft claim the items?

Yes! You can learn how to use the `/give` command from [here](https://minecraft.fandom.com/wiki/Commands/give)!


But you have to retype the commands for each type of item, so it's easier to accumulate items for a while and then collect them all at once in the game.


In fact, if you press the Tab key while typing a command, you can complete the input candidates, which saves you a lot of time.

Like this! ↓
![image](https://github.com/Foxy-null/AnkiCraft/assets/72304646/be271423-46f2-4463-9cd2-981342dd4477)


> Also one last comment (request) what is the addon that displays the total time this week and and last week?

Is this what you're looking for?
![image](https://github.com/Foxy-null/AnkiCraft/assets/72304646/a61baa18-a9fb-4ad5-b903-458b6e16e55e)

it's [More Decks Stats and Time addon](https://ankiweb.net/shared/info/1556734708)

If you like this add-on, I would appreciate it if you would star this repository!

Enjoy AnkiCraft life~!

**Comment by ShawnO33** [comment]
Thanks again!
