### ISSUE TITLE
[BUG] Gold Ingot Name

### ISSUE THREAD

**Issue by ohgollychan** [Foxy-null/AnkiCraft#14]
Gold ingots show up in Japanese. Language was set to English.

## To Reproduce
1. Open Anki
2. Collect a Gold Ingot
3. See error

## Screenshots (optional)
![image](https://github.com/Foxy-null/AnkiCraft/assets/68978882/84e9f93b-d212-4b66-b3ac-46369729fe51)

## Environment
 - OS: [e.g. Windows 11]
 - Anki Version: [e.g. 23.10]

**Comment by ohgollychan** [comment]
Also, a typo: "Deorite" → "Diorite"

**Comment by Foxy-null** [comment]
Thank you for letting me know! I'll go fix them!

**Comment by Foxy-null** [comment]
### Patched!
I'm going to publish it on AnkiWeb as well.
![image](https://github.com/Foxy-null/AnkiCraft/assets/72304646/1fb619ad-0595-457b-b2aa-419b63cd7585)
