### ISSUE TITLE
[BUG] Compatibility with 23.10

### ISSUE THREAD

**Issue by Rucia16311** [Foxy-null/AnkiCraft#7]
Here 

Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.4.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-01 19:07:40

When loading AnkiCraft:
Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "/Users/☆/Library/Application Support/Anki2/addons21/368161874/__init__.py", line 16, in <module>
    from . import main
  File "/Users/☆/Library/Application Support/Anki2/addons21/368161874/main.py", line 33, in <module>
    from .config import local_conf
  File "/Users/☆/Library/Application Support/Anki2/addons21/368161874/config.py", line 20, in <module>
    from .consts import *
  File "/Users/☆/Library/Application Support/Anki2/addons21/368161874/consts.py", line 26, in <module>
    addon_path = os.path.dirname(__file__).decode(sys_encoding)
AttributeError: 'str' object has no attribute 'decode'

**Comment by Foxy-null** [comment]
Thank you!!!
I'll take a look when I'm done studying today~!

**Comment by Foxy-null** [comment]
## I’m sorry, but if the same bug occurs in the non-beta version, I’ll take another look.

I debugged it for about 4 hours on three OSes: Windows 11, MacOS, and Linux (Ubuntu), and found that the bug you reported was caused by the fact that “PyQt5,” which should be included, could not be imported into Anki’s Python file due to some reason. 

There is no way that “PyQt5” is not included in Anki made with PyQt, so I think the reason why it cannot be imported is probably due to the fact that Anki is in beta.

**Comment by Rucia16311** [comment]
Thank you for your debugging.

 I forgot to mention that the report here is, I think, non-beta for 23.10, downloading the Qt6 one from the official site.(If this is what you call beta one, I'm sorry.) 

I don't know anything about programming, so all I can do is cheer and dance for you, but I look forward to being able to use it again!

**Comment by Foxy-null** [comment]
Woooow!!!!

I didn't know they have officially released 23.10!

Moreover, I've found some interesting [tips](https://forums.ankiweb.net/t/porting-tips-for-anki-23-10/35916) which may help to fix this issue.

I'm very busy these days so I can't do it right away, but I'll get it fixed for sure.

I will try my best to make AnkiCraft playable in your environment soon!

**Comment by Foxy-null** [comment]
I managed to fix all the errors, but for some reason **the items don't show up on the main menu.**
###  Please press **`Shift + T`** to check items until it is resolved.

Thanks for using AnkiCraft❤

(Check [the release](https://github.com/Foxy-null/AnkiCraft/releases/tag/v1.1.3) for detailed changes.)
